info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-09-07T01:26:46.414Z"}
info: Connected to the database. {"timestamp":"2022-09-07T01:26:55.703Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-09-07T01:38:16.814Z"}
info: Connected to the database. {"timestamp":"2022-09-07T01:38:20.471Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-09-07T02:41:12.386Z"}
info: Connected to the database. {"timestamp":"2022-09-07T02:41:21.217Z"}
error: 
    status - 500 
    message - ReferenceError: _id is not defined
    at _callee7$ (D:\CPF Batch\Fandoo-Notes\FandooNotes\src\services\/notes.service.js:53:5)
    at tryCatch (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.trashNotes (D:\CPF Batch\Fandoo-Notes\FandooNotes\src\services\/notes.service.js:50:24)
    at _callee7$ (D:\CPF Batch\Fandoo-Notes\FandooNotes\src\controllers\/notes.controller.js:132:41)
    at tryCatch (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/notes/63172f45ca3630068d37c18c/istrash 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-09-07T02:47:53.078Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-09-07T02:50:35.234Z"}
info: Connected to the database. {"timestamp":"2022-09-07T02:50:39.126Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-09-07T02:52:15.830Z"}
info: Connected to the database. {"timestamp":"2022-09-07T02:52:21.490Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-09-07T02:52:55.617Z"}
info: Connected to the database. {"timestamp":"2022-09-07T02:53:03.899Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-09-07T02:53:07.358Z"}
info: Connected to the database. {"timestamp":"2022-09-07T02:53:10.523Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-09-07T02:54:00.374Z"}
info: Connected to the database. {"timestamp":"2022-09-07T02:54:08.731Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-09-07T02:56:43.751Z"}
info: Connected to the database. {"timestamp":"2022-09-07T02:56:47.756Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ _id: undefined }" (type Object) at path "_id" for model "Notes"
    at model.Query.exec (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/notes/63172f45ca3630068d37c18c/istrash 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-09-07T02:57:04.493Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-09-07T02:57:56.369Z"}
info: Connected to the database. {"timestamp":"2022-09-07T02:58:05.359Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-09-07T02:58:23.924Z"}
info: Connected to the database. {"timestamp":"2022-09-07T02:58:29.439Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-09-07T03:14:05.049Z"}
info: Connected to the database. {"timestamp":"2022-09-07T03:14:13.911Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-09-07T05:33:05.803Z"}
info: Connected to the database. {"timestamp":"2022-09-07T05:33:15.261Z"}
error: 
    status - 500 
    message - ValidationError: Notes validation failed: Title: Path `Title` is required.
    at model.Document.invalidate (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\mongoose\lib\document.js:2782:32)
    at D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\mongoose\lib\document.js:2574:17
    at D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\mongoose\lib\schematype.js:1273:9
    at processTicksAndRejections (node:internal/process/task_queues:78:11) 
    url - /api/v1/notes 
    method - POST 
    IP - ::1
   {"timestamp":"2022-09-07T05:36:14.092Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-09-07T06:03:26.969Z"}
info: Connected to the database. {"timestamp":"2022-09-07T06:03:31.856Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-09-07T06:10:55.143Z"}
info: Connected to the database. {"timestamp":"2022-09-07T06:11:04.874Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-09-07T06:12:54.686Z"}
info: Connected to the database. {"timestamp":"2022-09-07T06:13:04.476Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-09-07T06:48:34.873Z"}
info: Connected to the database. {"timestamp":"2022-09-07T06:48:45.472Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-09-07T06:49:23.053Z"}
info: Connected to the database. {"timestamp":"2022-09-07T06:49:32.978Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-09-07T06:52:01.724Z"}
info: Connected to the database. {"timestamp":"2022-09-07T06:52:11.186Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-09-07T07:26:37.561Z"}
info: Connected to the database. {"timestamp":"2022-09-07T07:26:46.925Z"}
error: 
    status - 500 
    message - ValidationError: Notes validation failed: UserId: Path `UserId` is required.
    at model.Document.invalidate (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\mongoose\lib\document.js:2782:32)
    at D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\mongoose\lib\document.js:2574:17
    at D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\mongoose\lib\schematype.js:1273:9
    at processTicksAndRejections (node:internal/process/task_queues:78:11) 
    url - /api/v1/notes 
    method - POST 
    IP - ::1
   {"timestamp":"2022-09-07T07:30:50.331Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-09-07T07:34:34.240Z"}
info: Connected to the database. {"timestamp":"2022-09-07T07:34:43.314Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-09-07T07:37:47.114Z"}
info: Connected to the database. {"timestamp":"2022-09-07T07:37:56.594Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-09-07T07:46:45.751Z"}
info: Connected to the database. {"timestamp":"2022-09-07T07:46:55.030Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-09-07T07:50:15.394Z"}
info: Connected to the database. {"timestamp":"2022-09-07T07:50:25.051Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-09-07T10:24:43.030Z"}
info: Connected to the database. {"timestamp":"2022-09-07T10:24:51.655Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-09-07T10:28:24.195Z"}
info: Connected to the database. {"timestamp":"2022-09-07T10:28:28.342Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-09-07T10:31:45.677Z"}
info: Connected to the database. {"timestamp":"2022-09-07T10:31:56.186Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-09-07T10:34:48.760Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-09-07T10:34:59.212Z"}
info: Connected to the database. {"timestamp":"2022-09-07T10:35:04.670Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-09-07T10:35:15.087Z"}
info: Connected to the database. {"timestamp":"2022-09-07T10:35:19.355Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-09-07T10:37:26.390Z"}
info: Connected to the database. {"timestamp":"2022-09-07T10:37:35.184Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-09-07T10:39:49.149Z"}
info: Connected to the database. {"timestamp":"2022-09-07T10:39:58.427Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-09-07T10:40:29.899Z"}
info: Connected to the database. {"timestamp":"2022-09-07T10:40:35.676Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-09-07T10:46:45.995Z"}
info: Connected to the database. {"timestamp":"2022-09-07T10:46:55.264Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-09-07T11:32:59.774Z"}
info: Connected to the database. {"timestamp":"2022-09-07T11:33:09.645Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-09-07T11:51:39.087Z"}
info: Connected to the database. {"timestamp":"2022-09-07T11:51:53.094Z"}
error: 
    status - 500 
    message - MongooseError: Callback must be a function, got [object Object]
    at Function.Model.$handleCallbackError (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\mongoose\lib\model.js:5067:11)
    at Function.findByIdAndUpdate (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\mongoose\lib\model.js:2694:19)
    at _callee4$ (D:\CPF Batch\Fandoo-Notes\FandooNotes\src\services\/notes.service.js:25:30)
    at tryCatch (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.updateNotes (D:\CPF Batch\Fandoo-Notes\FandooNotes\src\services\/notes.service.js:24:25)
    at _callee4$ (D:\CPF Batch\Fandoo-Notes\FandooNotes\src\controllers\/notes.controller.js:72:41)
    at tryCatch (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21) 
    url - /api/v1/notes/6318818090c56efdf42a7b4f 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-09-07T11:52:28.063Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-09-07T11:54:35.949Z"}
info: Connected to the database. {"timestamp":"2022-09-07T11:54:48.901Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-09-07T12:00:23.565Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-09-07T12:00:26.930Z"}
info: Connected to the database. {"timestamp":"2022-09-07T12:00:36.552Z"}
error: 
    status - 500 
    message - ReferenceError: body is not defined
    at _callee6$ (D:\CPF Batch\Fandoo-Notes\FandooNotes\src\services\/notes.service.js:45:30)
    at tryCatch (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.archiveNotes (D:\CPF Batch\Fandoo-Notes\FandooNotes\src\services\/notes.service.js:42:26)
    at _callee6$ (D:\CPF Batch\Fandoo-Notes\FandooNotes\src\controllers\/notes.controller.js:112:41)
    at tryCatch (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/notes/6318818090c56efdf42a7b4f/isarchive 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-09-07T12:01:05.189Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-09-07T12:03:27.452Z"}
info: Connected to the database. {"timestamp":"2022-09-07T12:03:33.181Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-09-07T12:04:34.860Z"}
info: Connected to the database. {"timestamp":"2022-09-07T12:04:45.290Z"}
error: 
    status - 500 
    message - ReferenceError: id is not defined
    at _callee7$ (D:\CPF Batch\Fandoo-Notes\FandooNotes\src\services\/notes.service.js:59:18)
    at tryCatch (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.trashNotes (D:\CPF Batch\Fandoo-Notes\FandooNotes\src\services\/notes.service.js:56:24)
    at _callee7$ (D:\CPF Batch\Fandoo-Notes\FandooNotes\src\controllers\/notes.controller.js:132:41)
    at tryCatch (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPF Batch\Fandoo-Notes\FandooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/notes/6318818090c56efdf42a7b4f/istrash 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-09-07T12:04:56.934Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-09-07T12:05:19.154Z"}
info: Connected to the database. {"timestamp":"2022-09-07T12:05:28.824Z"}
